import { Router, type IRouter } from "express";
import healthRouter from "./health";
import overviewRouter from "./overview";
import employeesRouter from "./employees";
import shiftsRouter from "./shifts";
import inventoryRouter from "./inventory";
import salesRouter from "./sales";
import discountsRouter from "./discounts";
import reservationsRouter from "./reservations";
import analyticsRouter from "./analytics";
import menuRouter from "./menu";
import posRouter from "./pos";
import notificationsRouter from "./notifications";
import marketplaceRouter from "./marketplace";
import billingRouter from "./billing";
import reviewsRouter from "./reviews";
import loyaltyRouter from "./loyalty";
import platformRouter from "./platform";
import insightsRouter from "./insights";
import onboardingRouter from "./onboarding";
import campaignsRouter from "./campaigns";
import pilotRouter from "./pilot";
import attendanceRouter from "./attendance";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/overview", overviewRouter);
router.use("/employees", employeesRouter);
router.use("/shifts", shiftsRouter);
router.use("/inventory", inventoryRouter);
router.use("/sales", salesRouter);
router.use("/discounts", discountsRouter);
router.use("/reservations", reservationsRouter);
router.use("/analytics", analyticsRouter);
router.use("/menu", menuRouter);
router.use("/pos", posRouter);
router.use("/notifications", notificationsRouter);
router.use("/marketplace", marketplaceRouter);
router.use("/billing", billingRouter);
router.use("/reviews", reviewsRouter);
router.use("/loyalty", loyaltyRouter);
router.use("/platform", platformRouter);
router.use("/insights", insightsRouter);
router.use("/campaigns", campaignsRouter);
router.use("/pilot", pilotRouter);
router.use("/onboarding", onboardingRouter);
router.use("/attendance", attendanceRouter);

export default router;
