import { Router, type IRouter } from "express";
import healthRouter from "./health";
import overviewRouter from "./overview";
import employeesRouter from "./employees";
import shiftsRouter from "./shifts";
import inventoryRouter from "./inventory";
import salesRouter from "./sales";
import discountsRouter from "./discounts";
import reservationsRouter from "./reservations";
import analyticsRouter from "./analytics";
import menuRouter from "./menu";
import posRouter from "./pos";
import notificationsRouter from "./notifications";
import marketplaceRouter from "./marketplace";
import billingRouter from "./billing";
import reviewsRouter from "./reviews";
import loyaltyRouter from "./loyalty";
import platformRouter from "./platform";
import insightsRouter from "./insights";
import onboardingRouter from "./onboarding";
import campaignsRouter from "./campaigns";
import pilotRouter from "./pilot";
import attendanceRouter from "./attendance";
import availabilityRouter from "./availability";
import performanceRouter from "./performance";
import employeeDaysRouter from "./employee-days";
import employeeVacationsRouter from "./employee-vacations";
import bookingPlansRouter from "./booking-plans";
import profileRouter from "./profile";
import customerProfileRouter from "./customer-profile";
import mealPlanRouter from "./meal-plan";
import appFeedbackRouter from "./app-feedback";
import socialRouter from "./social";
import instantPlansRouter from "./instant-plans";
import promotionsRouter from "./promotions";
import founderRouter from "./founder";
import pricingRouter from "./pricing";
import businessClaimsRouter from "./business-claims";
import conversionRouter from "./conversion";
import variantsRouter from "./variants";
import competitionRouter from "./competition";
import citiesRouter from "./cities";
import opsRouter from "./ops";
import brainRouter from "./brain";
import teamRouter from "./team";
import walletRouter from "./wallet";
import authRouter from "./auth";
import oauthRouter from "./oauth";
import groupReservationsRouter from "./group-reservations";
import smartNotificationsRouter from "./smart-notifications";
import postsRouter from "./posts";
import publicProfileRouter from "./public-profile";
import messagesRouter from "./messages";
import moderationAdminRouter from "./moderation-admin";
import recommendationsRouter from "./recommendations";
import smartPlanRouter from "./smart-plan";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/overview", overviewRouter);
router.use("/employees", employeesRouter);
router.use("/shifts", shiftsRouter);
router.use("/inventory", inventoryRouter);
router.use("/sales", salesRouter);
router.use("/discounts", discountsRouter);
router.use("/reservations", reservationsRouter);
router.use("/analytics", analyticsRouter);
router.use("/menu", menuRouter);
router.use("/pos", posRouter);
router.use("/notifications", notificationsRouter);
router.use("/marketplace", marketplaceRouter);
router.use("/billing", billingRouter);
router.use("/reviews", reviewsRouter);
router.use("/loyalty", loyaltyRouter);
router.use("/platform", platformRouter);
router.use("/insights", insightsRouter);
router.use("/campaigns", campaignsRouter);
router.use("/pilot", pilotRouter);
router.use("/onboarding", onboardingRouter);
router.use("/attendance", attendanceRouter);
router.use("/availability", availabilityRouter);
router.use("/performance", performanceRouter);
router.use("/employee-days", employeeDaysRouter);
router.use("/employee-vacations", employeeVacationsRouter);
router.use("/booking-plans", bookingPlansRouter);
router.use("/profile", profileRouter);
router.use("/customer-profile", customerProfileRouter);
router.use("/meal-plan", mealPlanRouter);
router.use("/app-feedback", appFeedbackRouter);
router.use("/social", socialRouter);
router.use("/instant-plans", instantPlansRouter);
router.use("/promotions", promotionsRouter);
router.use("/founder", founderRouter);
router.use("/pricing", pricingRouter);
router.use("/business-claims", businessClaimsRouter);
router.use("/conversion", conversionRouter);
router.use("/variants", variantsRouter);
router.use("/competition", competitionRouter);
router.use("/cities", citiesRouter);
router.use("/ops", opsRouter);
router.use("/brain", brainRouter);
router.use("/team", teamRouter);
router.use("/wallet", walletRouter);
router.use("/auth", authRouter);
router.use("/auth", oauthRouter);
router.use("/group-reservations", groupReservationsRouter);
router.use("/smart-notifications", smartNotificationsRouter);
router.use("/posts", postsRouter);
router.use("/public-profile", publicProfileRouter);
router.use("/messages", messagesRouter);
router.use("/moderation", moderationAdminRouter);
router.use("/recommendations", recommendationsRouter);
router.use("/smart-plan", smartPlanRouter);

export default router;
